default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: schedule_tweets_development

test:
  <<: *default
  database: schedule_tweets_test

production:
  <<: *default
  database: schedule_tweets_production
  username: postgres
  password: <%= ENV['NEWOVERTIME_DATABASE_PASSWORD'] %>